(** This GCode was generated by ReplicatorG 0040 **)
(*  using Skeinforge (50)  *)
(*  for a Dual headed The Replicator  *)
(*  on 2017/08/02 21:07:16 (-0700) *)
(**** start.gcode for The Replicator, dual head ****)
M103 (disable RPM)
M73 P0 (enable build progress)
M73 P1 (display progress)
G21 (set units to mm)
G90 (set positioning to absolute)
M109 S110 T0 (set HBP temperature)
M73 P2 (display progress)
M104 S230 T0 (set extruder temperature) (temp updated by printOMatic)
(**** begin homing ****)
G162 X Y F2500 (home XY axes maximum)
M73 P3 (display progress)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 (move Z to "0")
M73 P4 (display progress)
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
(**** end homing ****)
M73 P5 (display progress)
G1 X-110.5 Y-74 Z150 F3300.0 (move to waiting position)
G130 X20 Y20 Z20 A20 B20 (Lower stepper Vrefs while heating)
M6 T0 (wait for toolhead, and HBP to reach temperature)
M73 P6 (display progress)
G130 X127 Y127 Z40 A127 B127 (Set Stepper motor Vref to defaults)
M108 R3.0 T0
G0 X-110.5 Y-74 (Position Nozzle)
M73 P7 (display progress)
G0 Z0.6      (Position Height)
M108 R5.0    (Set Extruder Speed)
M101         (Start Extruder)
M73 P8 (display progress)
G4 P2000     (Create Anchor)
(**** end of start.gcode ****)
(<format> skeinforge gcode </format>)
M73 P9 (display progress)
(<version> 12.03.14 </version>)
(<created> 17.08.02|21:7 </created>)
(<extruderInitialization>)
M73 P10 (display progress)
(<craftTypeName> extrusion </craftTypeName>)
M105
(<decimalPlacesCarried> 3 </decimalPlacesCarried>)
M73 P11 (display progress)
(<layerThickness> 0.2 </layerThickness>)
(<infillWidth> 0.5 </infillWidth>)
(<volumeFraction> 0.82 </volumeFraction>)
M73 P12 (display progress)
(<infillPerimeterOverlap> 0.3 </infillPerimeterOverlap>)
(<sharpestProduct> 0.866 </sharpestProduct>)
(<layerHeight> 0.2 </layerHeight>)
M73 P13 (display progress)
(<threadSequenceString> loops edge infill </threadSequenceString>)
(<maximumZFeedRatePerSecond> 999.0 </maximumZFeedRatePerSecond>)
(<objectFirstLayerFeedRateInfillMultiplier> 0.9 </objectFirstLayerFeedRateInfillMultiplier>)
M73 P14 (display progress)
(<operatingFeedRatePerSecond> 30.0 </operatingFeedRatePerSecond>)
(<objectFirstLayerFlowRateInfillMultiplier> 0.8 </objectFirstLayerFlowRateInfillMultiplier>)
(<operatingFlowRate> 30.0 </operatingFlowRate>)
M73 P15 (display progress)
(<orbitalFeedRatePerSecond> 0.0 </orbitalFeedRatePerSecond>)
(<travelFeedRatePerSecond> 150.0 </travelFeedRatePerSecond>)
(<skirtOutset> 1.75 </skirtOutset>)
M73 P16 (display progress)
M126
(<edgeWidth> 0.5 </edgeWidth>)
(<perimeterWidth> 0.5 </perimeterWidth>)
M73 P17 (display progress)
(<profileName> ABS </profileName>)
(<settings>)
(<setting> alteration Activate_Alteration True </setting>)
M73 P18 (display progress)
(<setting> alteration Name_of_End_File:  </setting>)
(<setting> alteration Name_of_Start_File:  </setting>)
(<setting> alteration Remove_Redundant_Mcode True </setting>)
M73 P19 (display progress)
(<setting> alteration Replace_Variable_with_Setting True </setting>)
(<setting> comb Activate_Comb True </setting>)
M73 P20 (display progress)
(<setting> comb Running_Jump_Space_(mm): 2.0 </setting>)
(<setting> cool Activate_Cool True </setting>)
(<setting> cool Bridge_Cool_(Celcius): 1.0 </setting>)
M73 P21 (display progress)
(<setting> cool Orbit False </setting>)
(<setting> cool Slow_Down True </setting>)
(<setting> cool Maximum_Cool_(Celcius): 1.0 </setting>)
M73 P22 (display progress)
(<setting> cool Minimum_Layer_Time_(seconds): 5.0 </setting>)
(<setting> cool Minimum_Orbital_Radius_(millimeters): 10.0 </setting>)
(<setting> cool Name_of_Cool_End_File: cool_end.gcode </setting>)
M73 P23 (display progress)
(<setting> cool Name_of_Cool_Start_File: cool_start.gcode </setting>)
(<setting> cool Orbital_Outset_(millimeters): 2.0 </setting>)
(<setting> cool Turn_Fan_On_at_Beginning True </setting>)
M73 P24 (display progress)
(<setting> cool Turn_Fan_Off_at_Ending True </setting>)
(<setting> dimension Activate_Dimension True </setting>)
(<setting> dimension Absolute_Extrusion_Distance True </setting>)
M73 P25 (display progress)
(<setting> dimension Relative_Extrusion_Distance False </setting>)
(<setting> dimension Extruder_Retraction_Speed_(mm/s): 20.0 </setting>)
(<setting> dimension Filament_Diameter_(mm): 1.82 </setting>)
M73 P26 (display progress)
(<setting> dimension Filament_Packing_Density_(ratio): 0.85 </setting>)
(<setting> dimension Maximum_E_Value_before_Reset_(float): 91234.0 </setting>)
(<setting> dimension Minimum_Travel_for_Retraction_(millimeters): 1.0 </setting>)
M73 P27 (display progress)
(<setting> dimension Retract_Within_Island False </setting>)
(<setting> dimension Retraction_Distance_(millimeters): 1.0 </setting>)
(<setting> dimension Restart_Extra_Distance_(millimeters): 0.0 </setting>)
M73 P28 (display progress)
(<setting> export Activate_Export True </setting>)
(<setting> export Add_Descriptive_Extension False </setting>)
(<setting> export Add_Export_Suffix False </setting>)
M73 P29 (display progress)
(<setting> export Add_Profile_Extension False </setting>)
(<setting> export Add_Timestamp_Extension False </setting>)
(<setting> export Also_Send_Output_To:  </setting>)
M73 P30 (display progress)
(<setting> export Analyze_Gcode True </setting>)
(<setting> export Do_Not_Delete_Comments True </setting>)
(<setting> export Delete_Crafting_Comments False </setting>)
M73 P31 (display progress)
(<setting> export Delete_All_Comments False </setting>)
(<setting> export Do_Not_Change_Output True </setting>)
(<setting> export binary_16_byte False </setting>)
M73 P32 (display progress)
(<setting> export gcode_step False </setting>)
(<setting> export gcode_time_segment False </setting>)
(<setting> export gcode_small False </setting>)
M73 P33 (display progress)
(<setting> export File_Extension: gcode </setting>)
(<setting> export Name_of_Replace_File: replace.csv </setting>)
(<setting> export Save_Penultimate_Gcode False </setting>)
M73 P34 (display progress)
(<setting> fill Activate_Fill True </setting>)
(<setting> fill Diaphragm_Period_(layers): 100 </setting>)
(<setting> fill Diaphragm_Thickness_(layers): 0 </setting>)
M73 P35 (display progress)
(<setting> fill Extra_Shells_on_Alternating_Solid_Layer_(layers): 3 </setting>)
(<setting> fill Extra_Shells_on_Base_(layers): 3 </setting>)
(<setting> fill Extra_Shells_on_Sparse_Layer_(layers): 3 </setting>)
M73 P36 (display progress)
(<setting> fill Grid_Circle_Separation_over_Perimeter_Width_(ratio): 0.2 </setting>)
(<setting> fill Grid_Extra_Overlap_(ratio): 0.1 </setting>)
(<setting> fill Grid_Junction_Separation_Band_Height_(layers): 10 </setting>)
M73 P37 (display progress)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_End_(ratio): 0.0 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_Middle_(ratio): 0.0 </setting>)
(<setting> fill Infill_Begin_Rotation_(degrees): 90.0 </setting>)
M73 P38 (display progress)
(<setting> fill Infill_Begin_Rotation_Repeat_(layers): 1 </setting>)
(<setting> fill Infill_Odd_Layer_Extra_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Grid_Circular False </setting>)
M73 P39 (display progress)
(<setting> fill Grid_Hexagonal False </setting>)
(<setting> fill Grid_Rectangular False </setting>)
M73 P40 (display progress)
(<setting> fill Line True </setting>)
(<setting> fill Infill_Perimeter_Overlap_(ratio): 0.3 </setting>)
(<setting> fill Infill_Solidity_(ratio): 0.5 </setting>)
M73 P41 (display progress)
(<setting> fill Sharpest_Angle_(degrees): 60.0 </setting>)
(<setting> fill Solid_Surface_Thickness_(layers): 3 </setting>)
(<setting> fill Lower_Left True </setting>)
M73 P42 (display progress)
(<setting> fill Nearest False </setting>)
(<setting> fill Surrounding_Angle_(degrees): 60.0 </setting>)
(<setting> fill Infill_>_Loops_>_Perimeter False </setting>)
M73 P43 (display progress)
(<setting> fill Infill_>_Perimeter_>_Loops False </setting>)
(<setting> fill Loops_>_Infill_>_Perimeter False </setting>)
(<setting> fill Loops_>_Perimeter_>_Infill True </setting>)
M73 P44 (display progress)
(<setting> fill Perimeter_>_Infill_>_Loops False </setting>)
(<setting> fill Perimeter_>_Loops_>_Infill False </setting>)
(<setting> home Activate_Home True </setting>)
M73 P45 (display progress)
(<setting> home Name_of_Home_File: home.gcode </setting>)
(<setting> jitter Activate_Jitter True </setting>)
(<setting> jitter Jitter_Over_Perimeter_Width_(ratio): 2.0 </setting>)
M73 P46 (display progress)
(<setting> skirt Activate_Skirt True </setting>)
(<setting> skirt Convex: True </setting>)
(<setting> skirt Gap_over_Perimeter_Width_(ratio): 3.0 </setting>)
M73 P47 (display progress)
(<setting> skirt Layers_To_(index): 1 </setting>)
(<setting> speed Activate_Speed True </setting>)
(<setting> speed Add_Flow_Rate: True </setting>)
M73 P48 (display progress)
(<setting> speed Bridge_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Bridge_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Beginning_(portion): 1.0 </setting>)
M73 P49 (display progress)
(<setting> speed Duty_Cyle_at_Ending_(portion): 0.0 </setting>)
(<setting> speed Feed_Rate_(mm/s): 30.0 </setting>)
(<setting> speed Flow_Rate_Setting_(float): 30.0 </setting>)
M73 P50 (display progress)
(<setting> speed Object_First_Layer_Feed_Rate_Infill_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Infill_Multiplier_(ratio): 0.8 </setting>)
M73 P51 (display progress)
(<setting> speed Object_First_Layer_Flow_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Orbital_Feed_Rate_over_Operating_Feed_Rate_(ratio): 0.0 </setting>)
(<setting> speed Maximum_Z_Feed_Rate_(mm/s): 999.0 </setting>)
M73 P52 (display progress)
(<setting> speed Perimeter_Feed_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Perimeter_Flow_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Travel_Feed_Rate_(mm/s): 150.0 </setting>)
M73 P53 (display progress)
(</settings>)
(<timeStampPreface> 20170802_210715 </timeStampPreface>)
(<procedureName> carve </procedureName>)
M73 P54 (display progress)
(<procedureName> preface </procedureName>)
(<procedureName> inset </procedureName>)
(<procedureName> fill </procedureName>)
M73 P55 (display progress)
(<procedureName> speed </procedureName>)
(<procedureName> skirt </procedureName>)
(<procedureName> jitter </procedureName>)
M73 P56 (display progress)
(<procedureName> comb </procedureName>)
(<procedureName> cool </procedureName>)
(<procedureName> dimension </procedureName>)
M73 P57 (display progress)
(<procedureName> alteration </procedureName>)
(<procedureName> export </procedureName>)
(</extruderInitialization>)
M73 P58 (display progress)
(<crafting>)
;M113 S1.0
;M108 R13.5
M73 P59 (display progress)
(<layer> 0.1 )
(<skirt>)
M73 P60 (display progress)
G1 X-1.75 Y51.75 Z0.1 F9000.0
G1 F1200.0
G1 E1.0
M73 P61 (display progress)
G1 F9000.0
M101
G1 X50.23 Y51.75 Z0.1 F810.0 E3.35
M73 P62 (display progress)
G1 X51.75 Y50.23 Z0.1 F810.0 E3.448
G1 X51.75 Y-1.75 Z0.1 F810.0 E5.798
G1 X-1.75 Y-1.75 Z0.1 F810.0 E8.218
M73 P63 (display progress)
G1 X-1.75 Y51.75 Z0.1 F810.0 E10.637
G1 F1200.0
G1 E9.637
M73 P64 (display progress)
G1 F810.0
M103
;M108 R13.5
M73 P65 (display progress)
(</skirt>)
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
M73 P66 (display progress)
(<boundaryPerimeter>)
(<boundaryPoint> X0.0 Y0.0 Z0.1 </boundaryPoint>)
(<boundaryPoint> X50.0 Y0.0 Z0.1 </boundaryPoint>)
M73 P67 (display progress)
(<boundaryPoint> X50.0 Y50.0 Z0.1 </boundaryPoint>)
(<boundaryPoint> X0.0 Y50.0 Z0.1 </boundaryPoint>)
(<edge> outer )
M73 P68 (display progress)
G1 X0.37 Y0.25 Z0.1 F9000.0
G1 F1200.0
G1 E10.637
M73 P69 (display progress)
G1 F9000.0
M101
G1 X49.75 Y0.25 Z0.1 F810.0 E12.87
M73 P70 (display progress)
G1 X49.75 Y49.75 Z0.1 F810.0 E15.109
G1 X0.25 Y49.75 Z0.1 F810.0 E17.347
G1 X0.25 Y0.25 Z0.1 F810.0 E19.586
M73 P71 (display progress)
G1 X0.37 Y0.25 Z0.1 F810.0 E19.591
G1 F1200.0
G1 E18.591
M73 P72 (display progress)
G1 F810.0
M103
(</edge>)
M73 P73 (display progress)
(</boundaryPerimeter>)
(<nestedRing>)
(<boundaryPerimeter>)
M73 P74 (display progress)
(<boundaryPoint> X48.0 Y48.0 Z0.1 </boundaryPoint>)
(<boundaryPoint> X48.0 Y2.0 Z0.1 </boundaryPoint>)
(<boundaryPoint> X2.0 Y2.0 Z0.1 </boundaryPoint>)
M73 P75 (display progress)
(<boundaryPoint> X2.0 Y48.0 Z0.1 </boundaryPoint>)
(<edge> inner )
G1 X1.75 Y1.87 Z0.1 F9000.0
M73 P76 (display progress)
G1 F1200.0
G1 E19.591
G1 F9000.0
M73 P77 (display progress)
M101
G1 X1.75 Y48.25 Z0.1 F810.0 E21.688
G1 X48.25 Y48.25 Z0.1 F810.0 E23.791
M73 P78 (display progress)
G1 X48.25 Y1.75 Z0.1 F810.0 E25.894
G1 X1.75 Y1.75 Z0.1 F810.0 E27.997
G1 X1.75 Y1.87 Z0.1 F810.0 E28.002
M73 P79 (display progress)
G1 F1200.0
G1 E28.002
M73 P80 (display progress)
G1 F810.0
M103
(</edge>)
M73 P81 (display progress)
(</boundaryPerimeter>)
(</nestedRing>)
(<loop> inner )
M73 P82 (display progress)
;M108 R24.0
G1 X1.63 Y1.25 Z0.1 F9000.0
G1 F1200.0
M73 P83 (display progress)
G1 E28.002
G1 F9000.0
M101
M73 P84 (display progress)
G1 X1.25 Y1.25 Z0.1 F1620.0 E28.018
G1 X1.25 Y48.75 Z0.1 F1620.0 E29.927
G1 X48.75 Y48.75 Z0.1 F1620.0 E31.836
M73 P85 (display progress)
G1 X48.75 Y1.25 Z0.1 F1620.0 E33.746
G1 X1.75 Y1.25 Z0.1 F1620.0 E35.635
G1 X1.63 Y1.25 Z0.1 F1620.0 E35.64
M73 P86 (display progress)
G1 F1200.0
G1 E35.64
G1 F1620.0
M73 P87 (display progress)
M103
(</loop>)
(<loop> outer )
M73 P88 (display progress)
G1 X1.87 Y0.75 Z0.1 F9000.0
G1 F1200.0
G1 E35.64
M73 P89 (display progress)
G1 F9000.0
M101
G1 X49.25 Y0.75 Z0.1 F1620.0 E37.544
M73 P90 (display progress)
G1 X49.25 Y49.25 Z0.1 F1620.0 E39.494
G1 X0.75 Y49.25 Z0.1 F1620.0 E41.443
G1 X0.75 Y0.75 Z0.1 F1620.0 E43.393
M73 P91 (display progress)
G1 X1.75 Y0.75 Z0.1 F1620.0 E43.433
G1 X1.87 Y0.75 Z0.1 F1620.0 E43.438
G1 F1200.0
M73 P92 (display progress)
G1 E42.438
G1 F1620.0
M103
M73 P93 (display progress)
(</loop>)
(</nestedRing>)
(</rotation>)
M73 P94 (display progress)
(</layer>)
(</crafting>)
M104 S0
M73 P95 (display progress)
;M113 S0.0
M127
(******* End.gcode*******)
M73 P96 (display progress)
M73 P100 ( End  build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
M73 P97 (display progress)
M109 S0 T0 ( Cool down the build platform )
M104 S0 T0 ( Cool down the Right Extruder )
M104 S0 T1 ( Cool down the Left Extruder )
M73 P98 (display progress)
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M73 P99 (display progress)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
